In [556]:
import pandas as pd
import numpy as np
import re

df = pd.read_excel("FORMULÁRIO GERAL DE RESULTADOS DAS CAMPANHAS DO LIMPA BRASIL.xlsx")

display(df)

,Carimbo de data/hora,Nome,E-mail,Telefone/Celular,"Representa alguma Organização/ONG/Escola/Empresa etc? Se sim, descreva o nome",Estado:,Cidade:,CEP,Participante como,Campanha,...,Endereço de e-mail,Limpeza ambiental,Limpeza de focos de dengue,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,CERTIFICADO
0,2021-03-09 14:26:44.684000,FRANCISCO DOS SANTOS BORGES,chicokaa@hotmail.com,+5598991850053,NaN,NaN,NaN,65062-630,Líder/Embaixador,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-03-09 22:11:13.925000,juliana de Souza Pinto Machado,julianadespmachado@gmail.com,+5554996715858,NaN,NaN,NaN,95670000,Voluntário,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-03-10 15:11:02.905000,Vanessa da Cruz,nessa.flower@hotmail.com,11972243169,NaN,NaN,NaN,08022-120,Líder/Embaixador,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-03-11 15:27:03.435000,Elen Borges dos Santos,elensantos0652@gmail.com,11951744807,NaN,NaN,NaN,08390-355,Voluntário,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-03-14 10:00:54.685000,75 Grupo Escoteiro Sao Thiago,familiafontella@yahoo.com.br,55- 99951-3532,NaN,Rio Grande do Sul,Santiago,97015070,Líder/Embaixador,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,2024-06-12 07:38:58.977000,Diego,Amigosdolarcliente@gmail.com,85-991586823,Limpa Brasil,Ceará,Fortaleza,60170241,Líder,Dia do Meio Ambiente,...,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN
186,2024-06-12 11:58:59.754000,Edmi Moreira,edmisoscerrado@yahoo.com.br,61981056929,Limpa Brasil,NaN,NaN,72220-060,Líder,Dia do Meio Ambiente,...,NaN,"O grupo saiu com sacos azuis e amarelos, divid...",NaN,Sim,NaN,NaN,NaN,NaN,NaN,NaN
187,2024-06-12 15:16:28.950000,Amanda Aymê Santos Bueno,greerevolutionpr@hotmail.com,4799977525,Green Revolution,Paraná,Curitiba,82700350,Líder,Dia do Meio Ambiente,...,NaN,NaN,NaN,Sim,Jhonatan Verres Clever . Natasha Dall Armi,NaN,NaN,NaN,NaN,NaN
188,2024-06-21 15:42:43.833000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,2024-10-07 12:22:09.438000,Edmi Moreira,edmisoscerrado@yahoo.com.br,61981056929,Sim INSTITUTO ECOS DO CERRADO,Distrito Federal,Recanto das Emas - Brasília,72220-060,Líder,Dia Mundial da Limpeza,...,NaN,Coleta seletiva,NaN,Sim,"Fabiana Alves Fernandes, Danielly Jeissy Pereira.",NaN,NaN,Não,NaN,NaN

In [557]:
#Nome

df['Nome'] = df['Nome'].astype(str)
df['Nome'] = df['Nome'].str.title()

display(df)

,Carimbo de data/hora,Nome,E-mail,Telefone/Celular,"Representa alguma Organização/ONG/Escola/Empresa etc? Se sim, descreva o nome",Estado:,Cidade:,CEP,Participante como,Campanha,...,Endereço de e-mail,Limpeza ambiental,Limpeza de focos de dengue,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,CERTIFICADO
0,2021-03-09 14:26:44.684000,Francisco Dos Santos Borges,chicokaa@hotmail.com,+5598991850053,NaN,NaN,NaN,65062-630,Líder/Embaixador,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-03-09 22:11:13.925000,Juliana De Souza Pinto Machado,julianadespmachado@gmail.com,+5554996715858,NaN,NaN,NaN,95670000,Voluntário,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-03-10 15:11:02.905000,Vanessa Da Cruz,nessa.flower@hotmail.com,11972243169,NaN,NaN,NaN,08022-120,Líder/Embaixador,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-03-11 15:27:03.435000,Elen Borges Dos Santos,elensantos0652@gmail.com,11951744807,NaN,NaN,NaN,08390-355,Voluntário,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-03-14 10:00:54.685000,75 Grupo Escoteiro Sao Thiago,familiafontella@yahoo.com.br,55- 99951-3532,NaN,Rio Grande do Sul,Santiago,97015070,Líder/Embaixador,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,2024-06-12 07:38:58.977000,Diego,Amigosdolarcliente@gmail.com,85-991586823,Limpa Brasil,Ceará,Fortaleza,60170241,Líder,Dia do Meio Ambiente,...,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN
186,2024-06-12 11:58:59.754000,Edmi Moreira,edmisoscerrado@yahoo.com.br,61981056929,Limpa Brasil,NaN,NaN,72220-060,Líder,Dia do Meio Ambiente,...,NaN,"O grupo saiu com sacos azuis e amarelos, divid...",NaN,Sim,NaN,NaN,NaN,NaN,NaN,NaN
187,2024-06-12 15:16:28.950000,Amanda Aymê Santos Bueno,greerevolutionpr@hotmail.com,4799977525,Green Revolution,Paraná,Curitiba,82700350,Líder,Dia do Meio Ambiente,...,NaN,NaN,NaN,Sim,Jhonatan Verres Clever . Natasha Dall Armi,NaN,NaN,NaN,NaN,NaN
188,2024-06-21 15:42:43.833000,Nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,2024-10-07 12:22:09.438000,Edmi Moreira,edmisoscerrado@yahoo.com.br,61981056929,Sim INSTITUTO ECOS DO CERRADO,Distrito Federal,Recanto das Emas - Brasília,72220-060,Líder,Dia Mundial da Limpeza,...,NaN,Coleta seletiva,NaN,Sim,"Fabiana Alves Fernandes, Danielly Jeissy Pereira.",NaN,NaN,Não,NaN,NaN

In [558]:
df['Telefone/Celular'] = df['Telefone/Celular'].astype(str)
df['Telefone/Celular'] = df['Telefone/Celular'].str.replace(" ", "").str.replace("-", "").str.replace("+55","")



def marcar_telefone_curto(numero):
    numero = str(numero)
    if len(numero) < 11:
        return numero + '*'
    return numero

df['Telefone/Celular'] = df['Telefone/Celular'].apply(marcar_telefone_curto)

display(df.iloc[23:28])

,Carimbo de data/hora,Nome,E-mail,Telefone/Celular,"Representa alguma Organização/ONG/Escola/Empresa etc? Se sim, descreva o nome",Estado:,Cidade:,CEP,Participante como,Campanha,...,Endereço de e-mail,Limpeza ambiental,Limpeza de focos de dengue,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,CERTIFICADO
23,2021-03-23 10:45:57.809000,Marcella,mn3678599@gmail.com,984758987*,NaN,NaN,NaN,65248000,Voluntário,#EuCuidodoMeuQuadrado,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2021-03-23 13:42:45.982000,Cleverton Da Silva,ecoimbe.rs@gmail.com,51991255250,NaN,Rio Grande do Sul,Imbé,95625-000,Líder/Embaixador,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2021-03-23 15:12:38.596000,Michelle Souza De Franca,michelle_november@hotmail.com,11982360132,NaN,NaN,NaN,04940010,Voluntário,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2021-03-23 18:42:45.391000,Jaqueline Araújo Pilar,jaquelineap@gmail.com,7747075593*,NaN,NaN,NaN,92310150,Líder/Embaixador,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2021-03-23 19:57:41.470000,Luciano,Lucianorgts@gmail.com,51981220900,NaN,NaN,NaN,92425100,Voluntário,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [559]:
#Organização

df['Representa alguma Organização/ONG/Escola/Empresa etc? Se sim, descreva o nome'] = df['Representa alguma Organização/ONG/Escola/Empresa etc? Se sim, descreva o nome'].astype(str)
df['Representa alguma Organização/ONG/Escola/Empresa etc? Se sim, descreva o nome'] = df['Representa alguma Organização/ONG/Escola/Empresa etc? Se sim, descreva o nome'].str.title()

In [560]:
#E-mail

df['E-mail'] = df['E-mail'].astype(str)
df['E-mail'] = df['E-mail'].str.lower()

df.loc[df['E-mail'].str.len() < 8, 'E-mail'] = np.nan
display(df.iloc[55:60])
#display(df)

,Carimbo de data/hora,Nome,E-mail,Telefone/Celular,"Representa alguma Organização/ONG/Escola/Empresa etc? Se sim, descreva o nome",Estado:,Cidade:,CEP,Participante como,Campanha,...,Endereço de e-mail,Limpeza ambiental,Limpeza de focos de dengue,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,CERTIFICADO
55,2021-04-05 12:32:44.364000,Danielson Mousan Dos Santos Vieira,luizamahin@gmail.com,7133142148*,Nan,Bahia,Salvador,40450210,Líder/Embaixador,#EuCuidodoMeuQuadrado,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,2021-04-05 15:30:48.415000,Patricia Sanfins,NaN,11996662928,Nan,São Paulo,Itatiba,13252300,Líder/Embaixador,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,2021-04-07 21:15:53.692000,32 Grupo Escoteiro Marquês De Olinda,alinaalcateia32@gmail.com,21993763752,Nan,NaN,NaN,20750 - 140,Voluntário,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,2021-04-14 19:09:33.591000,Anna Lerner,annalerner29@gmail.com,13981113002,Nao,NaN,NaN,11040270,Líder/Embaixador,Dia da Terra,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,2021-04-14 22:28:57.254000,Maria Luísa Machado De Oliveira,machadoo.marialuisa@gmail.com,31996340157,Não,NaN,NaN,35660369,Voluntário,#EuCuidodoMeuQuadrado,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [561]:
#CEP

df['CEP'] = df['CEP'].astype(str)
df['CEP'] = df['CEP'].str.lower()

df.loc[df['CEP'].str.len() < 8, 'E-mail'] = np.nan
df['CEP'] = df['CEP'].astype(str).str.zfill(8)
df['CEP'] = df['CEP'].str[:5] + '-' + df['CEP'].str[5:]



display(df.iloc[55:60])

,Carimbo de data/hora,Nome,E-mail,Telefone/Celular,"Representa alguma Organização/ONG/Escola/Empresa etc? Se sim, descreva o nome",Estado:,Cidade:,CEP,Participante como,Campanha,...,Endereço de e-mail,Limpeza ambiental,Limpeza de focos de dengue,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,CERTIFICADO
55,2021-04-05 12:32:44.364000,Danielson Mousan Dos Santos Vieira,luizamahin@gmail.com,7133142148*,Nan,Bahia,Salvador,40450-210,Líder/Embaixador,#EuCuidodoMeuQuadrado,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,2021-04-05 15:30:48.415000,Patricia Sanfins,NaN,11996662928,Nan,São Paulo,Itatiba,13252-300,Líder/Embaixador,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,2021-04-07 21:15:53.692000,32 Grupo Escoteiro Marquês De Olinda,alinaalcateia32@gmail.com,21993763752,Nan,NaN,NaN,20750- - 140,Voluntário,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,2021-04-14 19:09:33.591000,Anna Lerner,annalerner29@gmail.com,13981113002,Nao,NaN,NaN,11040-270,Líder/Embaixador,Dia da Terra,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,2021-04-14 22:28:57.254000,Maria Luísa Machado De Oliveira,machadoo.marialuisa@gmail.com,31996340157,Não,NaN,NaN,35660-369,Voluntário,#EuCuidodoMeuQuadrado,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [562]:
# ESTADO

# df['Estado:'] = df['Estado:'].astype(str)
# df_sp = df[df['Estado:'].str.lower() == 'são paulo']
# display(df_sp)

In [563]:
# df['Ação realizada em'] = df['Ação realizada em'].astype('datetime64[M]')

df['Ação realizada em'] = pd.to_datetime(df['Ação realizada em'], errors='coerce')  
df['Ação realizada em'] = df['Ação realizada em'].dt.to_period('M')

display(df)

,Carimbo de data/hora,Nome,E-mail,Telefone/Celular,"Representa alguma Organização/ONG/Escola/Empresa etc? Se sim, descreva o nome",Estado:,Cidade:,CEP,Participante como,Campanha,...,Endereço de e-mail,Limpeza ambiental,Limpeza de focos de dengue,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,CERTIFICADO
0,2021-03-09 14:26:44.684000,Francisco Dos Santos Borges,chicokaa@hotmail.com,98991850053,Nan,NaN,NaN,65062--630,Líder/Embaixador,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-03-09 22:11:13.925000,Juliana De Souza Pinto Machado,julianadespmachado@gmail.com,54996715858,Nan,NaN,NaN,95670-000,Voluntário,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-03-10 15:11:02.905000,Vanessa Da Cruz,nessa.flower@hotmail.com,11972243169,Nan,NaN,NaN,08022--120,Líder/Embaixador,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-03-11 15:27:03.435000,Elen Borges Dos Santos,elensantos0652@gmail.com,11951744807,Nan,NaN,NaN,08390--355,Voluntário,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-03-14 10:00:54.685000,75 Grupo Escoteiro Sao Thiago,familiafontella@yahoo.com.br,55999513532,Nan,Rio Grande do Sul,Santiago,97015-070,Líder/Embaixador,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,2024-06-12 07:38:58.977000,Diego,amigosdolarcliente@gmail.com,85991586823,Limpa Brasil,Ceará,Fortaleza,60170-241,Líder,Dia do Meio Ambiente,...,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN
186,2024-06-12 11:58:59.754000,Edmi Moreira,edmisoscerrado@yahoo.com.br,61981056929,Limpa Brasil,NaN,NaN,72220--060,Líder,Dia do Meio Ambiente,...,NaN,"O grupo saiu com sacos azuis e amarelos, divid...",NaN,Sim,NaN,NaN,NaN,NaN,NaN,NaN
187,2024-06-12 15:16:28.950000,Amanda Aymê Santos Bueno,greerevolutionpr@hotmail.com,4799977525*,Green Revolution,Paraná,Curitiba,82700-350,Líder,Dia do Meio Ambiente,...,NaN,NaN,NaN,Sim,Jhonatan Verres Clever . Natasha Dall Armi,NaN,NaN,NaN,NaN,NaN
188,2024-06-21 15:42:43.833000,Nan,NaN,nan*,Nan,NaN,NaN,00000-nan,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,2024-10-07 12:22:09.438000,Edmi Moreira,edmisoscerrado@yahoo.com.br,61981056929,Sim Instituto Ecos Do Cerrado,Distrito Federal,Recanto das Emas - Brasília,72220--060,Líder,Dia Mundial da Limpeza,...,NaN,Coleta seletiva,NaN,Sim,"Fabiana Alves Fernandes, Danielly Jeissy Pereira.",NaN,NaN,Não,NaN,NaN

In [564]:
#df['Data'] = pd.to_datetime(df['Data'])
df["Data"] = pd.to_datetime(df["Data"], errors='coerce')

display(df)

,Carimbo de data/hora,Nome,E-mail,Telefone/Celular,"Representa alguma Organização/ONG/Escola/Empresa etc? Se sim, descreva o nome",Estado:,Cidade:,CEP,Participante como,Campanha,...,Endereço de e-mail,Limpeza ambiental,Limpeza de focos de dengue,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,CERTIFICADO
0,2021-03-09 14:26:44.684000,Francisco Dos Santos Borges,chicokaa@hotmail.com,98991850053,Nan,NaN,NaN,65062--630,Líder/Embaixador,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-03-09 22:11:13.925000,Juliana De Souza Pinto Machado,julianadespmachado@gmail.com,54996715858,Nan,NaN,NaN,95670-000,Voluntário,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-03-10 15:11:02.905000,Vanessa Da Cruz,nessa.flower@hotmail.com,11972243169,Nan,NaN,NaN,08022--120,Líder/Embaixador,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-03-11 15:27:03.435000,Elen Borges Dos Santos,elensantos0652@gmail.com,11951744807,Nan,NaN,NaN,08390--355,Voluntário,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-03-14 10:00:54.685000,75 Grupo Escoteiro Sao Thiago,familiafontella@yahoo.com.br,55999513532,Nan,Rio Grande do Sul,Santiago,97015-070,Líder/Embaixador,Dia da Água,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,2024-06-12 07:38:58.977000,Diego,amigosdolarcliente@gmail.com,85991586823,Limpa Brasil,Ceará,Fortaleza,60170-241,Líder,Dia do Meio Ambiente,...,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN
186,2024-06-12 11:58:59.754000,Edmi Moreira,edmisoscerrado@yahoo.com.br,61981056929,Limpa Brasil,NaN,NaN,72220--060,Líder,Dia do Meio Ambiente,...,NaN,"O grupo saiu com sacos azuis e amarelos, divid...",NaN,Sim,NaN,NaN,NaN,NaN,NaN,NaN
187,2024-06-12 15:16:28.950000,Amanda Aymê Santos Bueno,greerevolutionpr@hotmail.com,4799977525*,Green Revolution,Paraná,Curitiba,82700-350,Líder,Dia do Meio Ambiente,...,NaN,NaN,NaN,Sim,Jhonatan Verres Clever . Natasha Dall Armi,NaN,NaN,NaN,NaN,NaN
188,2024-06-21 15:42:43.833000,Nan,NaN,nan*,Nan,NaN,NaN,00000-nan,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,2024-10-07 12:22:09.438000,Edmi Moreira,edmisoscerrado@yahoo.com.br,61981056929,Sim Instituto Ecos Do Cerrado,Distrito Federal,Recanto das Emas - Brasília,72220--060,Líder,Dia Mundial da Limpeza,...,NaN,Coleta seletiva,NaN,Sim,"Fabiana Alves Fernandes, Danielly Jeissy Pereira.",NaN,NaN,Não,NaN,NaN

In [565]:
df[["Peso total dos resíduos (kg)", "Quantidade total de itens coletados:     ","Galões", "Garrafas PET", "Pneus", "Copos/talheres/pratos", "Tampas/lacres/argolas de garrafa", "Sacos e sacolas", "Latas de bebida", "Latas (comida, desodorante, óleo, tinta, etc)", "Potes de vidro ou cerâmica", "Caixas de leite/suco, etc", "Balões e bexigas"]]


for coluna in df[["Galões", "Garrafas PET", "Pneus", "Copos/talheres/pratos", "Tampas/lacres/argolas de garrafa", "Sacos e sacolas", "Latas de bebida", "Latas (comida, desodorante, óleo, tinta, etc)", "Potes de vidro ou cerâmica", "Caixas de leite/suco, etc", "Balões e bexigas"]]:
    df[coluna] = pd.to_numeric(df[coluna], errors='coerce').fillna(0).astype(int)

In [566]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Columns: 145 entries, Carimbo de data/hora to CERTIFICADO
dtypes: datetime64[ns](1), float64(2), int64(11), object(130), period[M](1)
memory usage: 215.4+ KB

In [567]:
df.describe()

,Data,Copos/talheres/pratos,Galões,Garrafas PET,Sacos e sacolas,Tampas/lacres/argolas de garrafa,Balões e bexigas,Pneus,"Caixas de leite/suco, etc",Latas de bebida,"Latas (comida, desodorante, óleo, tinta, etc)",Potes de vidro ou cerâmica,Unnamed: 143,CERTIFICADO
count,86,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,0.0,64.000000
mean,2022-09-06 17:18:08.372092928,18.373684,1.731579,43.100000,36.705263,16.447368,4.663158,0.405263,3.726316,6.273684,1.636842,2.647368,NaN,0.046875
min,2020-03-19 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
25%,2022-03-22 06:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
50%,2022-06-05 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
75%,2023-07-22 00:00:00,5.750000,0.000000,11.750000,10.000000,7.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
max,2024-10-05 00:00:00,606.000000,134.000000,2560.000000,2470.000000,760.000000,800.000000,15.000000,100.000000,320.000000,36.000000,300.000000,NaN,1.000000
std,NaN,65.862309,10.651107,229.409884,200.981816,65.967162,58.047893,1.717933,11.615481,29.337461,5.941488,22.364864,NaN,0.213042

In [568]:
df = df.drop('Unnamed: 143', axis=1)

df.describe()

,Data,Copos/talheres/pratos,Galões,Garrafas PET,Sacos e sacolas,Tampas/lacres/argolas de garrafa,Balões e bexigas,Pneus,"Caixas de leite/suco, etc",Latas de bebida,"Latas (comida, desodorante, óleo, tinta, etc)",Potes de vidro ou cerâmica,CERTIFICADO
count,86,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,64.000000
mean,2022-09-06 17:18:08.372092928,18.373684,1.731579,43.100000,36.705263,16.447368,4.663158,0.405263,3.726316,6.273684,1.636842,2.647368,0.046875
min,2020-03-19 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2022-03-22 06:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2022-06-05 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2023-07-22 00:00:00,5.750000,0.000000,11.750000,10.000000,7.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2024-10-05 00:00:00,606.000000,134.000000,2560.000000,2470.000000,760.000000,800.000000,15.000000,100.000000,320.000000,36.000000,300.000000,1.000000
std,NaN,65.862309,10.651107,229.409884,200.981816,65.967162,58.047893,1.717933,11.615481,29.337461,5.941488,22.364864,0.213042

In [569]:
df_Novo = df[["Nome","CEP","Ação realizada em","Peso total dos resíduos (kg)", "Quantidade total de itens coletados:     ","Galões", "Garrafas PET", "Pneus", "Copos/talheres/pratos", "Tampas/lacres/argolas de garrafa", "Sacos e sacolas", "Latas de bebida", "Latas (comida, desodorante, óleo, tinta, etc)", "Potes de vidro ou cerâmica", "Caixas de leite/suco, etc", "Balões e bexigas"]]

df_Novo.head()

,Nome,CEP,Ação realizada em,Peso total dos resíduos (kg),Quantidade total de itens coletados:,Galões,Garrafas PET,Pneus,Copos/talheres/pratos,Tampas/lacres/argolas de garrafa,Sacos e sacolas,Latas de bebida,"Latas (comida, desodorante, óleo, tinta, etc)",Potes de vidro ou cerâmica,"Caixas de leite/suco, etc",Balões e bexigas
0,Francisco Dos Santos Borges,65062--630,1976-12,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0
1,Juliana De Souza Pinto Machado,95670-000,2021-03,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0
2,Vanessa Da Cruz,08022--120,2021-03,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0
3,Elen Borges Dos Santos,08390--355,2021-03,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0
4,75 Grupo Escoteiro Sao Thiago,97015-070,2021-03,320,245,11,58,8,36,67,56,68,36,43,17,0

In [570]:
df_Novo['Municipio'] = ""

C:\Users\36188635861\AppData\Local\Temp\ipykernel_3664\1017564458.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Novo['Municipio'] = ""

In [571]:
df_Novo = df_Novo[["Nome","CEP","Municipio","Ação realizada em","Peso total dos resíduos (kg)", "Quantidade total de itens coletados:     ","Galões", "Garrafas PET", "Pneus", "Copos/talheres/pratos", "Tampas/lacres/argolas de garrafa", "Sacos e sacolas", "Latas de bebida", "Latas (comida, desodorante, óleo, tinta, etc)", "Potes de vidro ou cerâmica", "Caixas de leite/suco, etc", "Balões e bexigas"]]

In [572]:
df_Novo.isnull().sum()

Nome                                               0
CEP                                                0
Municipio                                          0
Ação realizada em                                  6
Peso total dos resíduos (kg)                     120
Quantidade total de itens coletados:             124
Galões                                             0
Garrafas PET                                       0
Pneus                                              0
Copos/talheres/pratos                              0
Tampas/lacres/argolas de garrafa                   0
Sacos e sacolas                                    0
Latas de bebida                                    0
Latas (comida, desodorante, óleo, tinta, etc)      0
Potes de vidro ou cerâmica                         0
Caixas de leite/suco, etc                          0
Balões e bexigas                                   0
dtype: int64

In [573]:

#df_Novo['Peso total dos resíduos (kg)'] = df_Novo['Peso total dos resíduos (kg)'].fillna(0)
df_Novo.loc[pd.isna(df_Novo['Quantidade total de itens coletados:     ']), 'Quantidade total de itens coletados:     '] = 0
df_Novo.loc[pd.isna(df_Novo['Peso total dos resíduos (kg)']), 'Peso total dos resíduos (kg)'] = 0

In [574]:
df_Novo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Data columns (total 17 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Nome                                           190 non-null    object
 1   CEP                                            190 non-null    object
 2   Municipio                                      190 non-null    object
 3   Ação realizada em                              184 non-null    period[M]
 4   Peso total dos resíduos (kg)                   190 non-null    object
 5   Quantidade total de itens coletados:           190 non-null    object
 6   Galões                                         190 non-null    int64
 7   Garrafas PET                                   190 non-null    int64
 8   Pneus                                          190 non-null    int64
 9   Copos/talheres/pratos                          190 non-null    int64
 10  Tampas/lacres/argolas de garrafa               190 non-null    int64
 11  Sacos e sacolas                                190 non-null    int64
 12  Latas de bebida                                190 non-null    int64
 13  Latas (comida, desodorante, óleo, tinta, etc)  190 non-null    int64
 14  Potes de vidro ou cerâmica                     190 non-null    int64
 15  Caixas de leite/suco, etc                      190 non-null    int64
 16  Balões e bexigas                               190 non-null    int64
dtypes: int64(11), object(5), period[M](1)
memory usage: 25.4+ KB

In [575]:
df_Novo= df_Novo.drop(166)
df_Novo= df_Novo.drop(165)

display(df_Novo.iloc[164:169])

,Nome,CEP,Municipio,Ação realizada em,Peso total dos resíduos (kg),Quantidade total de itens coletados:,Galões,Garrafas PET,Pneus,Copos/talheres/pratos,Tampas/lacres/argolas de garrafa,Sacos e sacolas,Latas de bebida,"Latas (comida, desodorante, óleo, tinta, etc)",Potes de vidro ou cerâmica,"Caixas de leite/suco, etc",Balões e bexigas
164,Carolina Quelotti,30775-390,,2023-07,56.7,0,0,1650,0,0,0,1,320,0,0,1,0
167,Rafael Campos Batista,35162-450,,2023-08,0,1450,0,48,0,366,165,20,3,2,0,48,5
168,Fernanda Cubiaco,22040-001,,2023-09,20,1085,0,10,0,85,44,16,0,0,0,0,0
169,Natasha Itai Miyamoto,07111-010,,2023-09,0,0,2,52,1,6,57,25,7,3,5,5,5
170,Henrique Silva Cavalcanti,59082-210,,2023-10,0,2525,1,56,0,97,80,66,5,0,0,0,0

In [576]:
display(df_Novo)

,Nome,CEP,Municipio,Ação realizada em,Peso total dos resíduos (kg),Quantidade total de itens coletados:,Galões,Garrafas PET,Pneus,Copos/talheres/pratos,Tampas/lacres/argolas de garrafa,Sacos e sacolas,Latas de bebida,"Latas (comida, desodorante, óleo, tinta, etc)",Potes de vidro ou cerâmica,"Caixas de leite/suco, etc",Balões e bexigas
0,Francisco Dos Santos Borges,65062--630,,1976-12,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Juliana De Souza Pinto Machado,95670-000,,2021-03,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Vanessa Da Cruz,08022--120,,2021-03,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Elen Borges Dos Santos,08390--355,,2021-03,0,0,0,0,0,0,0,0,0,0,0,0,0
4,75 Grupo Escoteiro Sao Thiago,97015-070,,2021-03,320,245,11,58,8,36,67,56,68,36,43,17,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,Diego,60170-241,,2024-06,23,1230,0,32,0,8,29,8,17,0,0,21,0
186,Edmi Moreira,72220--060,,2024-06,0,0,0,18,0,30,19,8,0,0,0,18,0
187,Amanda Aymê Santos Bueno,82700-350,,2024-06,60,1000,0,150,1,25,12,18,6,2,6,6,0
188,Nan,00000-nan,,NaT,0,0,0,0,0,0,0,0,0,0,0,0,0
189,Edmi Moreira,72220--060,,2024-10,"139,445 kg",05,0,12,1,41,16,36,8,0,0,32,0

In [577]:
df_Novo.loc[df_Novo['Peso total dos resíduos (kg)'] == "139,445 kg", 'Peso total dos resíduos (kg)'] = 140
df_Novo['Peso total dos resíduos (kg)'] = df_Novo['Peso total dos resíduos (kg)'].astype(int)

In [578]:
# df_Novo['Quantidade total de itens coletados:     '] = df['Quantidade total de itens coletados:     '].str.replace("+", "").str.replace(" ", "").str.replace(",", ".")

df_Novo['Quantidade total de itens coletados:     '] = df_Novo['Quantidade total de itens coletados:     '].astype(int)

In [579]:
display(df_Novo)

,Nome,CEP,Municipio,Ação realizada em,Peso total dos resíduos (kg),Quantidade total de itens coletados:,Galões,Garrafas PET,Pneus,Copos/talheres/pratos,Tampas/lacres/argolas de garrafa,Sacos e sacolas,Latas de bebida,"Latas (comida, desodorante, óleo, tinta, etc)",Potes de vidro ou cerâmica,"Caixas de leite/suco, etc",Balões e bexigas
0,Francisco Dos Santos Borges,65062--630,,1976-12,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Juliana De Souza Pinto Machado,95670-000,,2021-03,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Vanessa Da Cruz,08022--120,,2021-03,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Elen Borges Dos Santos,08390--355,,2021-03,0,0,0,0,0,0,0,0,0,0,0,0,0
4,75 Grupo Escoteiro Sao Thiago,97015-070,,2021-03,320,245,11,58,8,36,67,56,68,36,43,17,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,Diego,60170-241,,2024-06,23,1230,0,32,0,8,29,8,17,0,0,21,0
186,Edmi Moreira,72220--060,,2024-06,0,0,0,18,0,30,19,8,0,0,0,18,0
187,Amanda Aymê Santos Bueno,82700-350,,2024-06,60,1000,0,150,1,25,12,18,6,2,6,6,0
188,Nan,00000-nan,,NaT,0,0,0,0,0,0,0,0,0,0,0,0,0
189,Edmi Moreira,72220--060,,2024-10,140,5,0,12,1,41,16,36,8,0,0,32,0

In [580]:
df_Novo.describe()

,Peso total dos resíduos (kg),Quantidade total de itens coletados:,Galões,Garrafas PET,Pneus,Copos/talheres/pratos,Tampas/lacres/argolas de garrafa,Sacos e sacolas,Latas de bebida,"Latas (comida, desodorante, óleo, tinta, etc)",Potes de vidro ou cerâmica,"Caixas de leite/suco, etc",Balões e bexigas
count,188.000000,188.000000,188.0000,188.000000,188.000000,188.000000,188.000000,188.000000,188.000000,188.000000,188.000000,188.000000,188.000000
mean,1033.111702,198.037234,1.7500,43.558511,0.409574,18.569149,16.622340,37.095745,6.340426,1.654255,2.675532,3.765957,4.712766
std,8953.503964,514.870186,10.7064,230.589878,1.726582,66.186016,66.296941,202.017687,29.486715,5.970752,22.482460,11.671003,58.355470
min,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,29.250000,34.000000,0.0000,13.250000,0.000000,6.250000,8.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,93195.000000,3622.000000,134.0000,2560.000000,15.000000,606.000000,760.000000,2470.000000,320.000000,36.000000,300.000000,100.000000,800.000000

In [581]:
df_Novo['CEP'] = df['CEP'].str.replace("--", "-").str.replace(" ", "").str.replace(".", "")

In [582]:
df_Novo.describe()

,Peso total dos resíduos (kg),Quantidade total de itens coletados:,Galões,Garrafas PET,Pneus,Copos/talheres/pratos,Tampas/lacres/argolas de garrafa,Sacos e sacolas,Latas de bebida,"Latas (comida, desodorante, óleo, tinta, etc)",Potes de vidro ou cerâmica,"Caixas de leite/suco, etc",Balões e bexigas
count,188.000000,188.000000,188.0000,188.000000,188.000000,188.000000,188.000000,188.000000,188.000000,188.000000,188.000000,188.000000,188.000000
mean,1033.111702,198.037234,1.7500,43.558511,0.409574,18.569149,16.622340,37.095745,6.340426,1.654255,2.675532,3.765957,4.712766
std,8953.503964,514.870186,10.7064,230.589878,1.726582,66.186016,66.296941,202.017687,29.486715,5.970752,22.482460,11.671003,58.355470
min,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,29.250000,34.000000,0.0000,13.250000,0.000000,6.250000,8.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,93195.000000,3622.000000,134.0000,2560.000000,15.000000,606.000000,760.000000,2470.000000,320.000000,36.000000,300.000000,100.000000,800.000000

In [583]:
df_Novo.to_excel("Base_Limpa_Brasil.xlsx", index=False)